language: python
python:
  - "3.6"
addons:
  ssh_known_hosts: 92.222.69.244
install: 
  - pip --version
  - git clone --branch=master https://github.com/kasztof/vosim.git kasztof/vosim
before_install:
  - openssl aes-256-cbc -K $encrypted_8940c4fcba27_key -iv $encrypted_8940c4fcba27_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key root@92.222.69.244 pwd
script:
  - ls
